version: "3"
services:
    jupyter_server:
        build:
            context: ./
        image: just-doc-it-jupyter-server:1.0.0
        ports:
            - 8888:8888
        working_dir: /opt
        command: >
            jupyter lab
                --ip '0.0.0.0'
                --notebook-dir ./notebooks
                --allow-root
                --no-browser
        volumes:
            - ./notebooks:/opt/notebooks
