#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOSQL
    CREATE DATABASE $DB_NAME;
    \connect $DB_NAME;
    CREATE SCHEMA $SCHEMA_NAME;
    CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
    GRANT ALL PRIVILEGES ON SCHEMA $SCHEMA_NAME TO $DB_USER;
    ALTER ROLE $DB_USER IN DATABASE $DB_NAME SET search_path TO $SCHEMA_NAME;
EOSQL
